### ISSUE TITLE
ModuleNotFoundError: No module name 'plugin'

### ISSUE THREAD

**Issue by frogmoses** [JASchilz/AnkiSyncDuolingo#15]
Windows 10, Anki 2.1.14 
Extracted the latest release into C:\Users\<user>\AppData\Roaming\Anki2\addons21. When opening Anki, get the following error:

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable the add-on.

When loading 'duolingo_sync':
Trackback (most recent call last):
File "aqt\addons.py, line 80, in loadAddons
File "C:\Users\<user>\AppData\Roaming\Anki2\addons21\duolingo_sync\__init__.py", line 1, in <module> import plugin ModuleNotFoundError: no module name 'plugin'

**Comment by JASchilz** [comment]
Ahah. The issue here is that the plugin was programmed for Anki 2.0.

I've finished updating this for Anki 2.1 and will upload this weekend.

**Comment by JASchilz** [comment]
Hi @frogmoses. You should now be able to follow the instructions in the README to install this for Anki 2.1.

I've packaged this as a `.ankiaddon`, so there should no longer be any need for unzipping files, etc.

**Comment by frogmoses** [comment]
Hi, I can confirm that this fixed the import problem. There is another issue with credentials that I will submit as a new bug.
