### ISSUE TITLE
After installing the latest version, uncaught exception is occurring when supplying credentials to Duolingo

### ISSUE THREAD

**Issue by frogmoses** [JASchilz/AnkiSyncDuolingo#17]
Steps:
1. Tools > SyncDuolingo
2. Prompt for Duolingo username and password
3. The error is generated

Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\<username>\AppData\Roaming\Anki2\addons21\duolingo_sync\plugin.py", line 64, in sync_duolingo
    lingo = Duolingo(username, password=password)
  File "C:\Users\<username>\AppData\Roaming\Anki2\addons21\duolingo_sync\duolingo.py", line 72, in __init__
    self.user_data = Struct(**self._get_data())
  File "C:\Users\<username>\AppData\Roaming\Anki2\addons21\duolingo_sync\duolingo.py", line 213, in _get_data
    get = self._make_req(self.user_url).json()
  File "lib\site-packages\requests\models.py", line 897, in json
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 342, in decode
<class 'json.decoder.JSONDecodeError'>: Extra data: line 1 column 5 (char 4)

**Comment by JASchilz** [comment]
Hmm...OK. Thanks for helping me troubleshoot any issues! First I want to confirm that I do have it working on my end:

![duolingo_login_big](https://user-images.githubusercontent.com/6137968/71324704-25bc9900-2497-11ea-89d2-16636bc51f52.gif)

I confirmed that my environment is very similar to yours, except that I'm running Anki 2.1.15. Based on the error, I doubt that this is at issue, though.

I've looked through the code, and it looks like the code is successfully logging you in, but then erroring out when it tries to retrieve information about your user.

I've got a couple of questions:
  1. Could you confirm that you're able to log in to the Duolingo site with your username and password, and then try the plugin again? It looks like you have your credentials correct, but I'm wondering if there's some kind of issue (like you have to confirm your e-mail address, or you haven't logged into the site for a year, or something like that) that isn't letting you completely log in.
  2. Do you have any characters other than the English alphabet in your username? If yes and this is the issue, then we should be able to find a fix.

Finally, here's a bit of code that can help us troubleshoot. If you're comfortable editing the plugin files, you can replace the `_get_data` method in the `duolingo.py` file around line 213 with the following:
```python
    def _get_data(self):
        """
        Get user's data from ``https://www.duolingo.com/users/<username>``.
        """
        raise Exception(self._make_req(self.user_url).content)
        # get = self._make_req(self.user_url).json()
        return get
```

If you're not sure how to do that, then I can build you a new version with this change that you can easily install.

This change will print out the body of the response that the duolingo library is unable to parse. I suspect it will have some kind of error in it that will tell us what to fix. It may include some information about your Duolingo account, like e-mail address, username, friends' usernames, etc., so if there's any part of that that you'd like to screen out take a look at it before pasting it back to me. It shouldn't contain anything super-sensitive like a password.

**Comment by frogmoses** [comment]
I found the issue. 

Duolingo allows you to login to the website with either your email address or a username. I was using my email address in your plug-in, as that is how I always login to Duolingo.

When I switched to using the username in your plug-in, it worked fine.

Thanks for your help and for developing this plug-in!

**Comment by JASchilz** [comment]
Yay! OK, I'll figure out a way to keep others from running into the same issue. :)

**Comment by Nanco300** [comment]
I can't login using credentials of the Google.

**Comment by JASchilz** [comment]
Hi Nancy! If I'm guessing correctly, you use sign-in-with-Google for Duolingo, but when you try to do that through the add-on, it tells you that your login/password are bad?

If that's the case, that's expected, and you'll need to create a login directly with Duolingo and use that to log in with the add-on.

I'm not sure how to do that off the top of my head, but I can see a lot of other users having the same problem. I'll make an update that addresses this.

**Comment by JASchilz** [comment]
Sorry, Nanco got autocorrected to Nancy.

I've created #18 to address this.

**Comment by JASchilz** [comment]
Hi Nanco! Can you try visiting https://www.duolingo.com/account and finding your username there?

And then if you don't know your Duolingo password, try setting it at https://www.duolingo.com/settings/password

And then use that username and password to log in with the add-on?
