### ISSUE TITLE
How do I know I am logged in to Duolingo, and that my cards are syncing?

### ISSUE THREAD

**Issue by seanmronan** [JASchilz/AnkiSyncDuolingo#19]
When going to Tools --> Sync Duolingo, I am asked to login with my Duolingo credentials, but I already did this the other day. Do I need to login every time I want to sync? Or should I just assume I am still logged in, and everything is syncing once I open Anki? There's no way to see whether or not my account is being synced.

I hope my question makes sense.

**Comment by JASchilz** [comment]
Ah! I understand. I think this is addressed a bit in the description on Anki, but not well enough.

Each time you "sync", it's a one time pull, not a thing that stays on and syncs each time. But I can see the word "sync" implying that once you get signed in the plugin will keep Anki in sync with Duolingo.

I think I can make this clearer by renaming the action to "Pull from Duolingo". And I'll include some language to describe that as you learn new words you can use the plugin again to pull in those new words.

**Comment by seanmronan** [comment]
Thank you so much for clarifying!

**Comment by JASchilz** [comment]
I've made the changes described above and will be publishing it immediately. Thanks for reporting this! It's got about 20 downloads so far, so I'm sure that other people would be getting the same impression.

Here are screenshots:

![image](https://user-images.githubusercontent.com/6137968/71626928-89844780-2ba4-11ea-94da-80b3f1e8ddc5.png)

![image](https://user-images.githubusercontent.com/6137968/71626961-afa9e780-2ba4-11ea-8455-cf87580f4326.png)

**Comment by JASchilz** [comment]
Alright. That new version is now published! I've also added a progress bar that will show progress while the add-on is logging you in.

**Comment by seanmronan** [comment]
Awesome work!
