### ISSUE TITLE
Add pronunciation support 

### ISSUE THREAD

**Issue by boba-and-beer** [JASchilz/AnkiSyncDuolingo#21]
Currently, it only supports Chinese in the following way: 
![image](https://user-images.githubusercontent.com/22341427/71757104-75638180-2ee7-11ea-9b6f-56bf67c42883.png)

It would help a lot to include the pin-yin just above the chinese word (or add pronunciation for character languages)

**Comment by boba-and-beer** [comment]
If anyone knows where to find the english pronunciations for character languages (e.g. pinyin for Chinese) in the duolingo API from [here](https://github.com/KartikTalwar/Duolingo/issues) then please let me know - happy to work on it otherwise I'll just use the normalized string which is just upper and lower case letters with no intonations (e.g. Xue Xiao)

**Comment by JASchilz** [comment]
I've merged #22, and will be tweaking the user experience. I'll close this when I publish!
