### ISSUE TITLE
Import from Duolingo isn't finishing

### ISSUE THREAD

**Issue by catie-patterson** [JASchilz/AnkiSyncDuolingo#28]
I've imported lots of notes from Duolingo, but lately my import never finishes.  Anki tells me the new notes have been added, but the "Importing from Duolingo" progress bar never finishes (see photo).
<img width="706" alt="Screen Shot 2020-12-23 at 1 11 47 PM" src="https://user-images.githubusercontent.com/5400992/103030073-af76ca80-4520-11eb-8d2b-bebb08671901.png">

When I eventually force quit Anki, the new notes aren't there.  Any ideas?

**Comment by JASchilz** [comment]
Hmm...does it seem like it could be stalling out on a particular word?

This weekend I'll try putting in an update that will make it list each word
as it's importing it. That could give some clues.

**Comment by catie-patterson** [comment]
I don't think it is a particular word.  I think I remember doing a big import of words recently, so maybe it's stalling out if there are only a few words?  Maybe the progress bar animation is taking longer to complete than the time it takes to download so few words?  I'm honestly not sure.  Once I build up more of a backlog of vocabulary, I'll try it again.  I definitely had this problem earlier this month, and then it randomly worked once.  So, that's why I'm thinking it may work with more words.  Unfortunately, I don't remember how many words I downloaded when it did work.

Really appreciate your help with this!  This is such a useful add-on!

**Comment by catie-patterson** [comment]
I'm even more convinced now that it is stalling out on lower numbers of words.  I've been trying every couple days to sync, and it finally worked today with 123.
<img width="518" alt="Screen Shot 2021-01-03 at 12 57 23 PM" src="https://user-images.githubusercontent.com/5400992/103486423-6c8be100-4dc3-11eb-816c-1ab7644df507.png">

Here is my (failed) attempt on 12/30 with 100 words:
<img width="671" alt="Screen Shot 2020-12-30 at 12 20 20 PM" src="https://user-images.githubusercontent.com/5400992/103486431-87f6ec00-4dc3-11eb-835c-8eb30f30451b.png">

**Comment by JASchilz** [comment]
Hi Catie! This helps me think through where the error might be. I'm unable to replicate this problem on my own machine: I've tried importing just 3 words and it's been successful each time. But I took a look at the plugin page on AnkiWeb and saw in the reviews that there were other people reporting this issue, so this isn't just you.

Since I can't replicate it, could you confirm or try a couple of things for me:
  * Could you upgrade to the latest version of Anki? You can download 2.1.38 from https://apps.ankiweb.net/ . There was a recent fix that might address this problem.
  * Could you make sure that you're on the latest version of _Pull from Duolingo_? You can re-install the plugin without losing any of your cards by going to "Tools" -> "Add ons" and then selecting and deleting the _Pull from Duolingo_ add-on. Then you can re-install the latest version using code 557761805.
  
 Just knowing that you're on the latest version of both of those will help us eliminate any easy problems.
 
 Your error report is very detailed, and I'm still trying to think through what kind of problem could produce the issue that you're seeing.

And if anyone else is joining this ticket, I'm curious if **you're seeing this problem on Windows or Linux**. I'm on Windows, and I see that you're on Mac, so I'm wondering if it possibly this only shows up on Mac.

**Comment by catie-patterson** [comment]
Hi Joseph!  I upgraded to Anki 2.1.38, and then attempted to import 6 words, and got the same stalling issue as before:
<img width="664" alt="Screen Shot 2021-01-03 at 3 47 43 PM" src="https://user-images.githubusercontent.com/5400992/103489677-b84a8480-4ddb-11eb-8f3b-27289c425bc2.png">

I then deleted and reinstalled your add-on.  When I tried importing from Duolingo again, I got the same issue.

Since you aren't able to reproduce the issue on your end, feel free to let me know if you need me to test anything else out.  Thanks so much for your help!

**Comment by JASchilz** [comment]
OK. Thank you for verifying that!

I still don't get what kind of problem would cause it to freeze up like this. But I did take a look at the plugin code and I saw:
  * When my plugin says "6 Notes Added", it's just naively assuming that every note it tried to add was successfully added.
  * But it looks like there's a way that I can ask Anki whether or not a note was successfully added.

So I've made a version of the add-on that will actually ask Anki whether the notes it's trying to add made it in. To install it, you'll need to:
  * download the duolingo_sync.ankiaddon from https://github.com/JASchilz/AnkiSyncDuolingo/releases/tag/1.1.2
  * delete the add-on that you currently have installed using the same add-on manager toolbox you used earlier today
  * then use the "install from file" option in the add-on manager to install this add-on

I **don't** think that this will solve the problem, but I am hoping that the window that now says "6 notes added" will say something like, "2 notes added. Failed to add: merci, chatte". I agree with you it's probably not a problem with certain words, but just knowing that my plugin can tell whether it was successful at adding a note will help with the debugging.

In this version, I also close the progress bar before I present the "X Notes Added" screen. I don't think that this will solve the crash, but it will help me troubleshoot.

When you try running this, can you tell me:
  * Do you see "Failed to add: ..." in the box that says "X notes added"
  * Do you see all of the words that you expected to add or just some? If you try to add the same vocabulary multiple times, then do the same words appear in the "Failed to add"?
  * Did the progress bar close out this time?
  * Are you able to click the "OK" button on the "X notes added" box? If so, what happens?
  * I've also added some debug logging. After attempting an import, you should be able to access this log by selecting "Pull from Duoling" in the addons toolbox, and then clicking "view files". The log will named log.txt. This log will contain all of the words that you attempted to sync, but doesn't contain anything personal like your username or password. Could you e-mail that to me (my e-mail is on my profile https://github.com/JASchilz) or post that here?

If this doesn't make the problem obvious, then

**Comment by catie-patterson** [comment]
It worked!  I was so shocked the first time it worked that I tried it again and recorded my screen.  I'll email you that recording since GitHub isn't letting me upload it.  I'll also include the log file in the email.  Thanks!

**Comment by catie-patterson** [comment]
Oh, I forgot to mention that I did search for the words that were supposed to be added, and they were in fact added.  Success!

**Comment by JASchilz** [comment]
Alright! Hmm...the only thing I really changed was the order of when the
progress bar window closes. So I'm also very surprised! :)

I'll try making a version with the logging, so that I can be sure that it's
not something mysterious about writing that log file that's saving the day.

--Joe

**Comment by cmcdevitt** [comment]
@JASchilz Well, I had the exact same issue. I pulled down your latest build and now it works! Thanks! Love this plugin!

**Comment by JASchilz** [comment]
Hi @cmcdevitt and @catie-patterson ! Thanks again for reporting this and helping me track it down.

I've made a release based on the version that solved your problem. I took out the logging/debugging and only left in the changes that I made to how the plugin closes the window.

I'm **hoping** that I left in the part that actually solves your problem! If you have an opportunity, could you re-install this from AnkiWeb? The code is 557761805. Could you let me know if this also works for you? Thank you! :)

**Comment by cmcdevitt** [comment]
@JASchilz Uninstalled and installed your new release. I will run this tomorrow after my Duo Lingo session.

**Comment by cmcdevitt** [comment]
@JASchilz I have had two pulls (over two days) successfully get the words from DuoLingo! Thanks

**Comment by JASchilz** [comment]
It sounds like this issue was resolved last year. Feel free to re-open it if the problem is re-occuring.

Also note that I recently overhauled the add-on for better compatibility with Anki versions 2.1.50+. I'd recommend upgrading to the latest version of the plugin if you're running into any weird problems.
