### ISSUE TITLE
Certain cards from French->English and German->English course have empty sources

### ISSUE THREAD

**Issue by thewithz** [JASchilz/AnkiSyncDuolingo#32]
Certain words like `J'ai` and `-cinq` don't have the corresponding English souces.
gid: 732305aab7ad26e739314d243adaa452 : j'ai
gid: 0704c1fbf6de919e793a14a63ac0927b : -cinq

**Comment by JASchilz** [comment]
Hi @TheWithz ! Thanks for reporting this. I found in #31 that some changes on the Duolingo servers are causing this problem. I haven't totally worked out how to get all of the changes, but the latest release of this plugin:
  * is able to get about 2/3rds of the missing translations
  * for the translations it can't get, it puts in a few words about how it wasn't able to find the translation, so the user has to edit it in.

I'm going to continue working on figuring out how to get all of the translations, but at least the note will let the user know about the problem.

I'd suggest upgrading to the latest version of the plugin with:
  * "Tools" -> "Add-ons"
  * Select "Pull from Duolingo"
  * Click "Check for Updates"

This update won't fill in any cards that you've already pulled from Duolingo, unless you delete those cards and re-pull them. But it should do a better job of filling in any new cards that you download.

**Comment by JASchilz** [comment]
Since #31 reports a similar issue (but in the German course), and since #31 also includes a separate issue about incorrect translations, I'm going to go ahead and make this the issue for tracking missing translations in _any_ course.

**Comment by JASchilz** [comment]
Hi @TheWithz . A user who reported a similar issue in German, now reports that the latest version of the plugin is able to get most of the English source/translations from Duolingo.

I've uploaded that latest version to AnkiWeb. I encourage you to upgrade to that version, and let me know how it's doing getting the French translations. I'm going to close this issue, but please let me know if it continues to present a problem!
