### ISSUE TITLE
Question: Can I change the name of the default deck and still pull from duolingo?

### ISSUE THREAD

**Issue by SakiHaryayin** [JASchilz/AnkiSyncDuolingo#38]
Hi, I am currently using my default deck to study a language and have pulled in several hundred cards from duolingo using this add-on. If I change the name of the deck to the language I am studying (e.g., English), can I continue to pull in new cards using this add-on? Thanks

**Comment by JASchilz** [comment]
Sorry I missed this question! I'm actually not sure about the behavior of Duolingo here. What I'd suggest is that if you try it out and the cards aren't landing where you want them to, then you can use the `duoling_sync` tag on all of the cards created by this plugin to help move them into the deck that you want them to go to.
