### ISSUE TITLE
Card order should probably be swapped

### ISSUE THREAD

**Issue by sliedes** [JASchilz/AnkiSyncDuolingo#39]
At least for learning Spanish, the order of the cards I get is

Card 1: Translate English to Spanish
Card 2: Translate Spanish to English

And this is the order Anki shows them in; once you have learned the English->Spanish, it will ask you Spanish-English.

This seems a bit backwards to me. It's generally easier to recognize foreign words than to be able to reproduce them. So I think the Target->Source card should be first.

**Comment by JASchilz** [comment]
Hmm...I think you're right about this one.

I'm going to swap the order. However, this won't effect anyone who already has the plugin installed, just new users. However, you can also change this order locally on your own collection:
  * Open Anki
  * Click "Tools" -> "Manage Note Types" -> Single click "Duolingo Sync" -> Then click the "Cards" button.
  * Now you can modify the cards associated with the note type. And if you click "Options" in the upper right then you can "reposition" the card types to achieve what you're describing.

Hopefully that helps! I'll leave this open until I can change the order for new users, which might take me a couple of weeks.
