### ISSUE TITLE
Kanji pronunciation is Chinese pronunciation

### ISSUE THREAD

**Issue by arskiir** [JASchilz/AnkiSyncDuolingo#40]
When pulled from duolingo, all cards that have kanji are read in the Chinese way (I believe?).

![image](https://user-images.githubusercontent.com/69001162/122149440-43996d00-ce86-11eb-99ea-d1ff2038f606.png)
![image](https://user-images.githubusercontent.com/69001162/122149223-eef5f200-ce85-11eb-8168-7ec5f8909240.png)

**Comment by JASchilz** [comment]
Hmm...I can see the problem! This might be something I can address on my end, or it might be a problem on Duolingo's end. I'm going to look into this, but it might be a couple of more weeks before I can get into it.

**Comment by JASchilz** [comment]
I'm going to combine this issue with #51: another issue which is particular to Japanese learners. I'd like to track Japanese issues in one place, for better organization and visibility.

The short story is that this _might or might not_ be an issue that is possible to fix in my code: it's also possible that there is some limitation to there is some limitation to the Duolingo API that I'm using that might just make it impossible for me to fix this.

And I'm figuring out that I probably don't have the time to address issues with specific languages/courses in Duolingo: I can only really focus on the big issues that hit all users. But if there are any programmers out there that are encountering this issue, then I'll give some guidance for how they might be able to fix it.

**Comment by JASchilz** [comment]
Duplicates #51 .

(Doesn't precisely duplicate it, but I'm combining all Japanese course issues there.)
