### ISSUE TITLE
Many words in source language

### ISSUE THREAD

**Issue by anwhitle** [JASchilz/AnkiSyncDuolingo#43]
On quite a few cards, there are many different words displayed in the source language that don't make sense. I speak English and am learning Portuguese.

For example:
The English card says "snake; (you) take; (you) collect; (he/she/it) asks for; (he/she/it) collects; (he/she/it) takes; (you) ask for; ask for!; cash; collect!; take!"
With the Portuguese translation being "cobra". Only the first word of "snake" should be on the card.

**Comment by JASchilz** [comment]
Hi Amwhitle, thank you for the report!

Hmm....I think I've seen this before and it's sometimes related to how the words are stored in Duolingo. This plugin reaches out to Duolingo for all of the translations, so if all of these words are incorrectly associated in the Duolingo database then that could be responsible for them appearing here.

I'll leave this ticket open in case other people are having the same problem, and I'll try to look into making some calls directly to Duolingo to see if maybe the plugin might be overreaching somehow.

**Comment by Koira-Pupu** [comment]
Hej

I, too have the same problem but with Finnish.

Source:
yes, he is; is spending; is; yes, I am; he is; are; have; yes, they are; it is; is having; does ... have; does; she is; yes, we are; has; do ... have; there are; we are; is it; yes, it is; yes, she is; they are; there is

Target:
on
---------------------

Source:
the dog; a dog; dog

Target:
koira

**Comment by JASchilz** [comment]
Closing this issue, as the plugin no longer provides translations at all. Some users have figured out workflows or other tools that they can use to provide translations in bulk (see https://github.com/JASchilz/AnkiSyncDuolingo/issues/61 ), and it's possible that these workflows or tools might address your issue.
