### ISSUE TITLE
Could you add config option to change name of deck from Default to any other?

### ISSUE THREAD

**Issue by DEC32768** [JASchilz/AnkiSyncDuolingo#44]
Could you add config option to change name of deck from Default to any other?

**Comment by JASchilz** [comment]
Hi @DEC32768 . This is a feature that I've seen a couple of requests for, and I can see how it would be useful.

I don't touch this plugin too much recently, except to fix bugs that might pop up when Duolingo makes changes to their code. So I probably won't be able to get around to this. But I will leave the request open to reflect that there are users asking for it.

Here are a couple of other resources or techniques that you might use:
  * https://docs.ankiweb.net/editing.html#using-decks-appropriately
  * Although plugin deposits all of its cards into Anki's default deck, it does add a tag that you can use to move those cards into another deck: after importing cards from Duolingo you can go into the Anki card browser and select all of the cards with tag:duolingo_sync from the default deck and move them into a deck of your choice.
