### ISSUE TITLE
Include sounds from Duolingo

### ISSUE THREAD

**Issue by ebanDev** [JASchilz/AnkiSyncDuolingo#47]
Could be awesome to have Duolingo's pronunciation when importing cards. Idk if it's possible from the API, but by scrapping I think it is.

**Comment by JASchilz** [comment]
This could definitely be a useful feature!

For the most part, I've stuck with the idea of this plugin only importing what it can from the Duolingo API. However, it from https://github.com/JASchilz/AnkiSyncDuolingo/issues/49, it looks like users have had some success applying other plugins to the cards created by this plugin, to create sounds/speech for their cards.
