### ISSUE TITLE
Incorporating AwesomeTTS or HyperTTS into Pull from Duolingo

### ISSUE THREAD

**Issue by fredrikcoulter** [JASchilz/AnkiSyncDuolingo#49]
Has anyone had any success incorporating either [AwesomeTTS](https://ankiweb.net/shared/info/1436550454) or [HyperTTS](https://ankiweb.net/shared/info/111623432) into Pull from Duolingo, perhaps by modifying the card type to incorporate verbal pronunciation?

**Comment by ghost** [comment]
Using AwesomeTTS with the source and destination fields as 'target' works for me after pulling.

**Comment by dougienisbet** [comment]
> Using AwesomeTTS with the source and destination fields as 'target' works for me after pulling.

Yes, same here. In fact one of the reasons I've revisited the Pull From Duolingo plugin is because I've installed the AwesomeTTS plugin. I like the voices and I like that they're different to the ones Duolingo uses.

**Comment by JASchilz** [comment]
Sounds like this is a thing that works without need for direct integration with the plugin.
