### ISSUE TITLE
Shows Multiple Words (Japanese)

### ISSUE THREAD

**Issue by Ag145** [JASchilz/AnkiSyncDuolingo#51]
In duolingo, there is feature which shows you an english word and makes you select the correct japanese translation. In anki, however, the cards only show you multiple words and there is no way to know which 
![Screenshot 2022-06-08 210731](https://user-images.githubusercontent.com/107133249/172659119-7753b703-7209-47dd-99b3-be470a8f6d7b.jpg)
![Screenshot 2022-06-08 210758](https://user-images.githubusercontent.com/107133249/172659122-bcdc6b8f-5577-4504-bef5-99384b3c6ef2.jpg)
word we need to translate.

**Comment by Ycmelon** [comment]
I don't think that's the issue here unless this problem exists outside of this card; in Japanese, しろ can refer to 白 (white), 城 (castle), or 為ろ (do) (I think)

**Comment by JASchilz** [comment]
Closing this issue, as the plugin no longer provides translations. Some users have figured out workflows or other tools that they can use to provide translations in bulk (see https://github.com/JASchilz/AnkiSyncDuolingo/issues/61 ).
