### ISSUE TITLE
Anki stuck on "Logging in..."

### ISSUE THREAD

**Issue by 3553x** [JASchilz/AnkiSyncDuolingo#55]
Hi,
upon entering a username and password two windows pop up. One states that "Duolingo Sync note type not found. Creating.", the other has a progress bar with the text "Logging in...". Anki gets stuck and I am unable to quit it. 

I have to manually kill the python3 process. This happens regardless of whether I use my account info or type something random. 

I'm on Linux and using Anki 2.1.54 with Python 3.10.6. I downloaded the plugin just now for the first time and have never had it installed previously.

**Comment by JASchilz** [comment]
Thanks for reporting this!

I'm able to reproduce the issue by starting with a totally fresh install of
Anki. I think my recent refactor to bring the plugin up-to-date with recent
versions of Anki neglected this case of a new user.

Look for a fix by tomorrow.

**Comment by JASchilz** [comment]
OK! I believe that this is now fixed. Could you try re-installing/updating
the add-on? After updating the add-on, you'll have to restart Anki before
the change will take effect.

**Comment by 3553x** [comment]
Thank you, I updated the add-on and the issue no longer exists. Entering a wrong password also displays an error popup and does not freeze Anki.
