### ISSUE TITLE
Error Message: Could Not Get Translations

### ISSUE THREAD

**Issue by mayamadeagithub** [JASchilz/AnkiSyncDuolingo#60]
Hello.
How do I fix this error message:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-20 17:43:56

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Maya\AppData\Roaming\Anki2\addons21\557761805\duolingo.py", line 448, in get_translations
    return request.json()
  File "requests\models.py", line 900, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Maya\AppData\Roaming\Anki2\addons21\557761805\plugin.py", line 96, in sync_duolingo
    translations = lingo.get_translations([vocab['word_string'] for vocab in word_chunk])
  File "C:\Users\Maya\AppData\Roaming\Anki2\addons21\557761805\duolingo.py", line 450, in get_translations
    raise Exception('Could not get translations')
Exception: Could not get translations

**Comment by JASchilz** [comment]
Hi @mayamadeagithub . Thanks for reporting this.

It looks like Duolingo has changed something about their service and specifically the way programs can reach out to Duolingo to get translations. The AnkiSyncDuolingo plugin uses a third party code library to talk to Duolingo, and other users of that library are reporting an issue similar to yours.

So it looks like this isn't a thing that I can readily fix, and other people will be running into the same problem as you. I'm going to post a prominent notice that (at the current time, anyway) this plugin is broken. I'll look into the issue more this weekend, but as it's a holiday I might not get a chance to really look into it until December 3rd.

**Comment by JASchilz** [comment]
I'm actually going to close this one in favor of #59 . Please follow that for a resolution, as they seem to be the same issue. Once again, thanks for raising this.
