### ISSUE TITLE
Error with Anki 2.1.56

### ISSUE THREAD

**Issue by jameskraus** [JASchilz/AnkiSyncDuolingo#63]
This add-on worked with 2.1.54, but after upgrading to 2.1.56 it fails. After downgrading to 2.1.54 it's working again.

**Comment by JASchilz** [comment]
Thanks for reporting! I'll check it out this weekend.

**Comment by JASchilz** [comment]
Just wanted to check in and say that I haven't been able to look at this
yet, but it's still on my radar.

**Comment by JASchilz** [comment]
Hi @jameskraus . I've tested [the release candidate based on your PR](https://github.com/JASchilz/AnkiSyncDuolingo/releases/tag/2.1.0rc1) under Anki 2.1.60 using both QT5 and QT6 and am unable to reproduce the issue.

Perhaps your changes address the issue? Could you let me know if the issue persists for you using that release candidate with Anki 2.1.60?

**Comment by jameskraus** [comment]
Yup, looks like it's working now. Cool!
