### ISSUE TITLE
Spanish on both sides

### ISSUE THREAD

**Issue by mickmel** [JASchilz/AnkiSyncDuolingo#68]
I got the plugin to work successfully, and it synced, but the data isn't good, as there is no English answer.

I get questions like: "Provide the translation for 'este' from Spanish." and the answer is "este".

![este](https://user-images.githubusercontent.com/4370849/226112812-60e68c00-54c2-4e12-ba2d-dfdd3fba5598.png)

Any ideas? Thanks!

**Comment by JASchilz** [comment]
Hi @mickmel ! Providing translations isn't a feature of this plugin.

It would definitely be a useful thing to have, and in fact the plugin used to provide this feature, but Duolingo changed their code and turned off the functionality that the plugin used to retrieve the translation.

The field where it says, "Provide the translation for 'este' from Spanish," is where the user needs to provide the translation from Spanish.

Some other users have figured out ways to use other tools to provide these translations in bulk. You can see that discussion in https://github.com/JASchilz/AnkiSyncDuolingo/issues/61 .
