### ISSUE TITLE
Both sides of flashcards in other language

### ISSUE THREAD

**Issue by alzprojects** [JASchilz/AnkiSyncDuolingo#73]
One side of the card says:

Provide the translation for 'אמא' from Hebrew. To Hebrew:

Other Side Says:

אמא
<img width="324" alt="Screenshot 2023-08-02 161428" src="https://github.com/JASchilz/AnkiSyncDuolingo/assets/114770643/51be7206-a7bb-4c5a-97ee-0ef7cd22c68f">

**Comment by JASchilz** [comment]
Hi @alzprojects ! As mentioned in the plugin description (https://ankiweb.net/shared/info/557761805) this plugin does not provide translations.

I'll go ahead and close this request, but let me know if I missed the point and there was something else being requested!
