### ISSUE TITLE
Allow any note-type with a Gid field, not just the single pre-ordained note-type

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [JASchilz/AnkiSyncDuolingo#75]
My language cards use a bunch of different note types for different purposes, with different fields and generated-cards:

<img width="243" alt="Screenshot 2023-11-05 at 20 17 05" src="https://github.com/JASchilz/AnkiSyncDuolingo/assets/200/4fee82b2-e517-43bc-bfa4-2837ce38f25b">

Skimming the code, it doesn't look like this addon needs to know anything about the _existing_ card's note-type — just whether it exists. I took a brief stab at patching this, but I couldn't quite get a Python dev-environment setup within my allocated time. 😅

This should only require patching the following to use the field's name, instead of its index, to find the gid:

https://github.com/JASchilz/AnkiSyncDuolingo/blob/2c712177f0daff0e4332d3513735c1602e9f9b26/duolingo_sync/plugin.py#L42-L44

(Ideally, in the process, it'd be nice to have the field renamed to "Duolingo GID" or something clearer, too.)

**Comment by JASchilz** [comment]
I appreciate your thoughts and suggestions here @ELLIOTTCABLE , and this seems like a reasonable idea.

In https://github.com/JASchilz/AnkiSyncDuolingo/issues/78 I call out that I'm not able to give this project the full attention that I'd like to as owner, that I'm unable to provide or consider merge requests for new features, and invite a new maintainer.

If a new owner shows up in #78 , then you could potentially let them know about this idea. :)
